# Generated by Django 5.1.5 on 2025-01-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=20)),
                ("receiver", models.CharField(max_length=20)),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "whatsapp_message_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["sender"], name="whatsapp_wh_sender_f8c769_idx"
                    ),
                    models.Index(
                        fields=["receiver"], name="whatsapp_wh_receive_6d3f35_idx"
                    ),
                    models.Index(
                        fields=["status"], name="whatsapp_wh_status_55e250_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="whatsapp_wh_timesta_795c73_idx"
                    ),
                ],
            },
        ),
    ]
